
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jul 27 10:30:30 CST 2020
//----------------------------------------------------

package octaladecimal.cup;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int OCTAL = 2;
  public static final int ERROR = 3;
  public static final int error = 1;
  public static final int EOF = 0;
}

